"""Data models for the isolated Phase 1 STEM support framework.

This module contains response schemas shared by the STEM detector and service
layer. Future feature-specific payloads for formula assistance, symbol
explanation, diagram explanation, step-by-step solutions, and scientific
vocabulary simplification should be added here as the STEM module grows.
"""

from dataclasses import dataclass


@dataclass
class STEMDetectionResult:
    """Summary of STEM content detected in extracted document text.

    Counts are generated by the Phase 1 placeholder detector. Future versions
    may add confidence scores, source spans, and routing metadata while keeping
    this base summary stable for UI integration.
    """

    has_formula: bool
    has_symbols: bool
    has_diagrams: bool
    formula_count: int
    symbol_count: int
    diagram_count: int
