"""Curated STEM symbol explanations for dyslexic learners.

The library gives fast, consistent offline responses for common STEM symbols.
Unknown symbols are handled by a safe fallback in ``symbol_assistant.py``.
"""

from __future__ import annotations

from typing import Any


SYMBOL_LIBRARY: dict[str, dict[str, Any]] = {
    "\u03a3": {
        "symbol": "\u03a3",
        "meaning": "Summation",
        "simple_explanation": "Used to add many values together.",
        "similar_symbols": ["E"],
        "difference": "\u03a3 means add values, unlike the letter E.",
        "example": "\u03a3(1, 2, 3) = 6",
    },
    "\u222b": {
        "symbol": "\u222b",
        "meaning": "Integral",
        "simple_explanation": "Used to add tiny parts together.",
        "similar_symbols": ["f"],
        "difference": "\u222b adds tiny parts, unlike the letter f.",
        "example": "\u222b can find area under a graph.",
    },
    "\u03c0": {
        "symbol": "\u03c0",
        "meaning": "Pi",
        "simple_explanation": "Helps measure circles.",
        "similar_symbols": ["n"],
        "difference": "\u03c0 is a circle number, unlike variable n.",
        "example": "Use \u03c0 to find a circle's area.",
    },
    "\u221e": {
        "symbol": "\u221e",
        "meaning": "Infinity",
        "simple_explanation": "Means something goes on forever.",
        "similar_symbols": ["8"],
        "difference": "\u221e means endless, unlike the number 8.",
        "example": "A line can continue toward \u221e.",
    },
    "\u221a": {
        "symbol": "\u221a",
        "meaning": "Square Root",
        "simple_explanation": "Finds a number that makes another number.",
        "similar_symbols": ["v"],
        "difference": "\u221a asks for a root, unlike the letter v.",
        "example": "\u221a9 = 3",
    },
    "\u2248": {
        "symbol": "\u2248",
        "meaning": "Approximately Equal",
        "simple_explanation": "Means two values are almost the same.",
        "similar_symbols": ["="],
        "difference": "\u2248 means close, while = means exact.",
        "example": "3.14 \u2248 \u03c0",
    },
    "\u2260": {
        "symbol": "\u2260",
        "meaning": "Not Equal",
        "simple_explanation": "Means two values are different.",
        "similar_symbols": ["="],
        "difference": "\u2260 means different, while = means same.",
        "example": "5 \u2260 3",
    },
    "\u2264": {
        "symbol": "\u2264",
        "meaning": "Less Or Equal",
        "simple_explanation": "Means smaller than or the same.",
        "similar_symbols": ["<"],
        "difference": "\u2264 allows equal, while < does not.",
        "example": "x \u2264 10",
    },
    "\u2265": {
        "symbol": "\u2265",
        "meaning": "Greater Or Equal",
        "simple_explanation": "Means bigger than or the same.",
        "similar_symbols": [">"],
        "difference": "\u2265 allows equal, while > does not.",
        "example": "score \u2265 50",
    },
    "\u00b1": {
        "symbol": "\u00b1",
        "meaning": "Plus Minus",
        "simple_explanation": "Means add or subtract this amount.",
        "similar_symbols": ["+"],
        "difference": "\u00b1 gives two choices, while + only adds.",
        "example": "10 \u00b1 2 means 8 or 12.",
    },
    "\u221d": {
        "symbol": "\u221d",
        "meaning": "Proportional To",
        "simple_explanation": "Means two amounts change together.",
        "similar_symbols": ["\u221e"],
        "difference": "\u221d shows a link, while \u221e means endless.",
        "example": "speed \u221d distance",
    },
    "\u2208": {
        "symbol": "\u2208",
        "meaning": "Element Of",
        "simple_explanation": "Means something belongs to a group.",
        "similar_symbols": ["E"],
        "difference": "\u2208 shows membership, unlike the letter E.",
        "example": "3 \u2208 {1, 2, 3}",
    },
    "\u2209": {
        "symbol": "\u2209",
        "meaning": "Not Element",
        "simple_explanation": "Means something is not in a group.",
        "similar_symbols": ["\u2208"],
        "difference": "\u2209 means not inside, while \u2208 means inside.",
        "example": "4 \u2209 {1, 2, 3}",
    },
    "\u222a": {
        "symbol": "\u222a",
        "meaning": "Union",
        "simple_explanation": "Joins two groups together.",
        "similar_symbols": ["U"],
        "difference": "\u222a joins groups, unlike the letter U.",
        "example": "{1, 2} \u222a {3} = {1, 2, 3}",
    },
    "\u2229": {
        "symbol": "\u2229",
        "meaning": "Intersection",
        "simple_explanation": "Shows what two groups share.",
        "similar_symbols": ["n"],
        "difference": "\u2229 shows overlap, unlike the letter n.",
        "example": "{1, 2} \u2229 {2, 3} = {2}",
    },
    "\u0394": {
        "symbol": "\u0394",
        "meaning": "Change",
        "simple_explanation": "Shows how much something changes.",
        "similar_symbols": ["A"],
        "difference": "\u0394 means change, unlike the letter A.",
        "example": "\u0394x means change in position.",
    },
    "\u03bb": {
        "symbol": "\u03bb",
        "meaning": "Lambda",
        "simple_explanation": "Often shows wavelength.",
        "similar_symbols": ["Y"],
        "difference": "\u03bb is Greek, unlike the English letter Y.",
        "example": "\u03bb can show the length of a wave.",
    },
    "\u03b8": {
        "symbol": "\u03b8",
        "meaning": "Theta",
        "simple_explanation": "Often shows an angle.",
        "similar_symbols": ["O", "0"],
        "difference": "\u03b8 can mean angle, unlike O or 0.",
        "example": "\u03b8 can label an angle in a triangle.",
    },
    "\u03a9": {
        "symbol": "\u03a9",
        "meaning": "Ohm",
        "simple_explanation": "Used for electrical resistance.",
        "similar_symbols": ["O"],
        "difference": "\u03a9 measures resistance, unlike the letter O.",
        "example": "A resistor can measure 10 \u03a9.",
    },
    "\u03bc": {
        "symbol": "\u03bc",
        "meaning": "Mu",
        "simple_explanation": "Often shows a tiny unit or average.",
        "similar_symbols": ["u"],
        "difference": "\u03bc is Greek, unlike the English letter u.",
        "example": "\u03bcm means micrometer.",
    },
    "\u03b1": {
        "symbol": "\u03b1",
        "meaning": "Alpha",
        "simple_explanation": "Often names an angle or value.",
        "similar_symbols": ["a"],
        "difference": "\u03b1 is Greek, unlike the English letter a.",
        "example": "\u03b1 can label an angle in geometry.",
    },
    "\u03b2": {
        "symbol": "\u03b2",
        "meaning": "Beta",
        "simple_explanation": "Often names a second angle or value.",
        "similar_symbols": ["B"],
        "difference": "\u03b2 is Greek, unlike the English letter B.",
        "example": "\u03b2 can label another angle.",
    },
    "\u03b3": {
        "symbol": "\u03b3",
        "meaning": "Gamma",
        "simple_explanation": "Often names rays, values, or angles.",
        "similar_symbols": ["y"],
        "difference": "\u03b3 is Greek, unlike the English letter y.",
        "example": "\u03b3 rays are high-energy rays.",
    },
    "\u03c1": {
        "symbol": "\u03c1",
        "meaning": "Rho",
        "simple_explanation": "Often shows density.",
        "similar_symbols": ["p"],
        "difference": "\u03c1 often means density, unlike letter p.",
        "example": "\u03c1 can mean mass per volume.",
    },
    "\u03c3": {
        "symbol": "\u03c3",
        "meaning": "Sigma",
        "simple_explanation": "Often shows spread in data.",
        "similar_symbols": ["o"],
        "difference": "\u03c3 can show spread, unlike letter o.",
        "example": "\u03c3 shows standard deviation.",
    },
    "\u03c4": {
        "symbol": "\u03c4",
        "meaning": "Tau",
        "simple_explanation": "Often shows time or turning force.",
        "similar_symbols": ["t"],
        "difference": "\u03c4 is Greek, unlike the English letter t.",
        "example": "\u03c4 can mean torque.",
    },
    "\u03c9": {
        "symbol": "\u03c9",
        "meaning": "Omega",
        "simple_explanation": "Often shows angular speed.",
        "similar_symbols": ["w"],
        "difference": "\u03c9 is Greek, unlike the English letter w.",
        "example": "\u03c9 can show spin speed.",
    },
    "\u22a5": {
        "symbol": "\u22a5",
        "meaning": "Perpendicular",
        "simple_explanation": "Means two lines meet at a square corner.",
        "similar_symbols": ["T"],
        "difference": "\u22a5 means right angle, unlike letter T.",
        "example": "Wall \u22a5 floor",
    },
    "\u00b0": {
        "symbol": "\u00b0",
        "meaning": "Degree",
        "simple_explanation": "Measures angles or temperature.",
        "similar_symbols": ["o"],
        "difference": "\u00b0 is a unit mark, unlike letter o.",
        "example": "90\u00b0 is a right angle.",
    },
    "\u2207": {
        "symbol": "\u2207",
        "meaning": "Nabla",
        "simple_explanation": "Shows change across space.",
        "similar_symbols": ["\u0394"],
        "difference": "\u2207 shows direction change, while \u0394 shows change.",
        "example": "\u2207T shows temperature changes.",
    },
    "\u2202": {
        "symbol": "\u2202",
        "meaning": "Partial",
        "simple_explanation": "Shows change in one part.",
        "similar_symbols": ["d"],
        "difference": "\u2202 shows partial change, unlike letter d.",
        "example": "\u2202x means change in x only.",
    },
    "\u2297": {
        "symbol": "\u2297",
        "meaning": "Tensor Product",
        "simple_explanation": "Combines two math objects.",
        "similar_symbols": ["x"],
        "difference": "\u2297 is a special product, unlike letter x.",
        "example": "A \u2297 B combines two matrices.",
    },
    "\u2295": {
        "symbol": "\u2295",
        "meaning": "Direct Sum",
        "simple_explanation": "Combines parts without mixing them.",
        "similar_symbols": ["+"],
        "difference": "\u2295 is special adding, unlike regular +.",
        "example": "A \u2295 B keeps spaces separate.",
    },
    "\u2225": {
        "symbol": "\u2225",
        "meaning": "Parallel",
        "simple_explanation": "Means two lines never meet.",
        "similar_symbols": ["||"],
        "difference": "\u2225 means parallel, while || can mean or.",
        "example": "Railway tracks are \u2225.",
    },
    "\u2220": {
        "symbol": "\u2220",
        "meaning": "Angle",
        "simple_explanation": "Shows the space between two lines.",
        "similar_symbols": ["<"],
        "difference": "\u2220 marks an angle, unlike the less-than sign.",
        "example": "\u2220ABC names an angle.",
    },
    "\u21cc": {
        "symbol": "\u21cc",
        "meaning": "Equilibrium",
        "simple_explanation": "Shows a reaction can go both ways.",
        "similar_symbols": ["="],
        "difference": "\u21cc shows two directions, unlike equals.",
        "example": "A + B \u21cc C",
    },
    "\u2192": {
        "symbol": "\u2192",
        "meaning": "Produces",
        "simple_explanation": "Shows what comes next or is made.",
        "similar_symbols": ["-"],
        "difference": "\u2192 shows direction, unlike a dash.",
        "example": "H\u2082 + O\u2082 \u2192 H\u2082O",
    },
    "\u2190": {
        "symbol": "\u2190",
        "meaning": "Comes From",
        "simple_explanation": "Shows movement or reaction to the left.",
        "similar_symbols": ["-"],
        "difference": "\u2190 points left, unlike a dash.",
        "example": "Product \u2190 reactants",
    },
    "x\u0304": {
        "symbol": "x\u0304",
        "meaning": "Mean",
        "simple_explanation": "Shows the average of x values.",
        "similar_symbols": ["x"],
        "difference": "x\u0304 means average, unlike plain x.",
        "example": "x\u0304 = 5 means the average is 5.",
    },
    "\u2200": {
        "symbol": "\u2200",
        "meaning": "For All",
        "simple_explanation": "Means something is true for every item.",
        "similar_symbols": ["A"],
        "difference": "\u2200 means every, unlike the letter A.",
        "example": "\u2200x means for every x.",
    },
    "\u2203": {
        "symbol": "\u2203",
        "meaning": "There Exists",
        "simple_explanation": "Means at least one item exists.",
        "similar_symbols": ["E"],
        "difference": "\u2203 means exists, unlike the letter E.",
        "example": "\u2203x means some x exists.",
    },
    "\u00d7": {
        "symbol": "\u00d7",
        "meaning": "Multiply",
        "simple_explanation": "Means groups are combined by times.",
        "similar_symbols": ["x"],
        "difference": "\u00d7 multiplies, unlike the letter x.",
        "example": "3 \u00d7 4 = 12",
    },
    "\u00f7": {
        "symbol": "\u00f7",
        "meaning": "Divide",
        "simple_explanation": "Means split into equal parts.",
        "similar_symbols": ["-"],
        "difference": "\u00f7 divides, unlike a minus sign.",
        "example": "12 \u00f7 3 = 4",
    },
    "\u2205": {
        "symbol": "\u2205",
        "meaning": "Empty Set",
        "simple_explanation": "Means a group has nothing in it.",
        "similar_symbols": ["0"],
        "difference": "\u2205 is no items, unlike the number 0.",
        "example": "No answers means set \u2205.",
    },
    "\u2282": {
        "symbol": "\u2282",
        "meaning": "Subset",
        "simple_explanation": "Means one group is inside another.",
        "similar_symbols": ["C"],
        "difference": "\u2282 means inside a set, unlike letter C.",
        "example": "{1, 2} \u2282 {1, 2, 3}",
    },
    "\u2286": {
        "symbol": "\u2286",
        "meaning": "Subset Or Equal",
        "simple_explanation": "Means inside or exactly the same.",
        "similar_symbols": ["\u2282"],
        "difference": "\u2286 allows equal sets, while \u2282 does not.",
        "example": "{1, 2} \u2286 {1, 2}",
    },
    "\u2206": {
        "symbol": "\u2206",
        "meaning": "Increment",
        "simple_explanation": "Shows a small change.",
        "similar_symbols": ["\u0394"],
        "difference": "\u2206 is a change mark, like uppercase \u0394.",
        "example": "\u2206t means a small time change.",
    },
    "\u03c6": {
        "symbol": "\u03c6",
        "meaning": "Phi",
        "simple_explanation": "Often names an angle or special value.",
        "similar_symbols": ["o"],
        "difference": "\u03c6 is Greek, unlike the English letter o.",
        "example": "\u03c6 can label an angle.",
    },
    "\u03c7": {
        "symbol": "\u03c7",
        "meaning": "Chi",
        "simple_explanation": "Often appears in statistics.",
        "similar_symbols": ["x"],
        "difference": "\u03c7 is Greek, unlike the English letter x.",
        "example": "\u03c7\u00b2 is used in statistics.",
    },
    "\u2113": {
        "symbol": "\u2113",
        "meaning": "Script L",
        "simple_explanation": "Often shows length or a line.",
        "similar_symbols": ["l"],
        "difference": "\u2113 is a math symbol, unlike letter l.",
        "example": "\u2113 can mean length.",
    },
}


def get_symbol_explanation(symbol: str) -> dict[str, Any] | None:
    """Return a curated symbol explanation when available."""

    explanation = SYMBOL_LIBRARY.get((symbol or "").strip())
    if explanation is None:
        return None

    return {
        "symbol": explanation["symbol"],
        "meaning": explanation["meaning"],
        "simple_explanation": explanation["simple_explanation"],
        "similar_symbols": list(explanation["similar_symbols"]),
        "difference": explanation["difference"],
        "example": explanation["example"],
    }
